spring:
  cloud:
    gateway:
      routes:
        - id: msvc-users
          uri: ${CLIENTS_USUARIOS_URL:http://localhost:8001}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: msvc-courses
          uri: ${CLIENTS_CURSOS_URL:http://localhost:8002}
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=2