spring:
  cloud:
    gateway:
      routes:
        - id: msvc-users
          uri: ${CLIENTS_USUARIOS_URL:http://localhost:8001}
          predicates:
            - Path=/api/users/**
        - id: msvc-courses
          uri: ${CLIENTS_CURSOS_URL:http://localhost:8002}
          predicates:
            - Path=/api/courses/**
      default-filters:
        - AddResponseHeader=X-Response-Time, #{T(java.lang.System).currentTimeMillis() - T(org.springframework.web.server.ServerWebExchange).getAttribute('startTime')}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true