version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-usuarios
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: msvc_usuarios
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  msvc-usuarios:
    build:
      context: .
      dockerfile: ./msvc-usuarios/Dockerfile
    container_name: msvc-usuarios
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/msvc_usuarios?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
    networks:
      - microservicios-network

  postgresql:
    image: postgres:15-alpine
    container_name: postgres-cursos
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: msvc_cursos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  msvc-cursos:
    build:
      context: .
      dockerfile: ./msvc-cursos/Dockerfile
    container_name: msvc-cursos
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/msvc_cursos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgresql
    networks:
      - microservicios-network

volumes:
  mysql-data:
  postgres-data:

networks:
  microservicios-network:
    driver: bridge

