services:
  mysql:
    image: mysql:8.0
    container_name: mysql-usuarios
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: msvc_usuarios
      MYSQL_USER: msvc_user
      MYSQL_PASSWORD: msvc_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservicios-network

  postgresql:
    image: postgres:15-alpine
    container_name: postgres-cursos
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: msvc_cursos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservicios-network

# Para arrancar el network usar: docker network create microservicios-network
networks:
  microservicios-network:
    external: true
    name: microservicios-network

volumes:
  mysql-data:
  postgres-data:

