# Configuracion del puerto y nombre de la aplicacion
server.port=8002

# Datos de la aplicacion
spring.application.name=msvc-cursos

# Configuracion de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/msvc_cursos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion del cliente Feign
clients.usuarios.url=${CLIENTS_USUARIOS_URL:http://localhost:8001}

# Configuracion de logging
logging.level.org.hibernate.SQL=debug