# Configuración del puerto y nombre de la aplicación
server.port=8002

# Datos de la aplicación
spring.application.name=msvc-cursos

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/msvc_cursos
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de logging
logging.level.org.hibernate.SQL=debug